Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/nbclient/client.py", line 1093, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/nbclient/client.py", line 559, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/nbclient/client.py", line 854, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/nbclient/client.py", line 756, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
fig, axs = plt.subplots(1, 3, figsize=(18, 6))

heatmap(Bhat,
        vmin=0,
        vmax=1,
        font_scale=1.5,
        title="$\hat B_{SBM}$",
        ax=axs[0])

heatmap(np.array(B),
        vmin=0,
        vmax=1,
        font_scale=1.5,
        title="$B_{SBM}$",
        ax=axs[1])

heatmap(np.abs(Bhat - np.array(B)),
        vmin=0,
        vmax=1,
        font_scale=1.5,
        title="$|\hat B_{SBM} - B_{SBM}|$",
        ax=axs[2])

fig;
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mValueError[0m                                Traceback (most recent call last)
Input [0;32mIn [34][0m, in [0;36m<module>[0;34m[0m
[1;32m      3[0m heatmap(Bhat,
[1;32m      4[0m         vmin[38;5;241m=[39m[38;5;241m0[39m,
[1;32m      5[0m         vmax[38;5;241m=[39m[38;5;241m1[39m,
[1;32m      6[0m         font_scale[38;5;241m=[39m[38;5;241m1.5[39m,
[1;32m      7[0m         title[38;5;241m=[39m[38;5;124m"[39m[38;5;124m$[39m[38;5;124m\[39m[38;5;124mhat B_[39m[38;5;132;01m{SBM}[39;00m[38;5;124m$[39m[38;5;124m"[39m,
[1;32m      8[0m         ax[38;5;241m=[39maxs[[38;5;241m0[39m])
[1;32m     10[0m heatmap(np[38;5;241m.[39marray(B),
[1;32m     11[0m         vmin[38;5;241m=[39m[38;5;241m0[39m,
[1;32m     12[0m         vmax[38;5;241m=[39m[38;5;241m1[39m,
[1;32m     13[0m         font_scale[38;5;241m=[39m[38;5;241m1.5[39m,
[1;32m     14[0m         title[38;5;241m=[39m[38;5;124m"[39m[38;5;124m$B_[39m[38;5;132;01m{SBM}[39;00m[38;5;124m$[39m[38;5;124m"[39m,
[1;32m     15[0m         ax[38;5;241m=[39maxs[[38;5;241m1[39m])
[0;32m---> 17[0m heatmap(np[38;5;241m.[39mabs([43mBhat[49m[43m [49m[38;5;241;43m-[39;49m[43m [49m[43mnp[49m[38;5;241;43m.[39;49m[43marray[49m[43m([49m[43mB[49m[43m)[49m),
[1;32m     18[0m         vmin[38;5;241m=[39m[38;5;241m0[39m,
[1;32m     19[0m         vmax[38;5;241m=[39m[38;5;241m1[39m,
[1;32m     20[0m         font_scale[38;5;241m=[39m[38;5;241m1.5[39m,
[1;32m     21[0m         title[38;5;241m=[39m[38;5;124m"[39m[38;5;124m$|[39m[38;5;124m\[39m[38;5;124mhat B_[39m[38;5;132;01m{SBM}[39;00m[38;5;124m - B_[39m[38;5;132;01m{SBM}[39;00m[38;5;124m|$[39m[38;5;124m"[39m,
[1;32m     22[0m         ax[38;5;241m=[39maxs[[38;5;241m2[39m])
[1;32m     24[0m fig

[0;31mValueError[0m: operands could not be broadcast together with shapes (2,2) (3,3) 
ValueError: operands could not be broadcast together with shapes (2,2) (3,3) 

